spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods_manager?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1908218002zjl
  application:
    name: service
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: arbiterarbiterarbiterarbiterarbiterarbiter
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization

#打印mybatis-plus日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl